from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from raamatu_teenus.models.base_model import Model
from raamatu_teenus import util


class RaamatuNimekiri200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, raamatud=None):  # noqa: E501
        """RaamatuNimekiri200Response - a model defined in OpenAPI

        :param raamatud: The raamatud of this RaamatuNimekiri200Response.  # noqa: E501
        :type raamatud: List[str]
        """
        self.openapi_types = {
            'raamatud': List[str]
        }

        self.attribute_map = {
            'raamatud': 'raamatud'
        }

        self._raamatud = raamatud

    @classmethod
    def from_dict(cls, dikt) -> 'RaamatuNimekiri200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The raamatuNimekiri_200_response of this RaamatuNimekiri200Response.  # noqa: E501
        :rtype: RaamatuNimekiri200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def raamatud(self) -> List[str]:
        """Gets the raamatud of this RaamatuNimekiri200Response.


        :return: The raamatud of this RaamatuNimekiri200Response.
        :rtype: List[str]
        """
        return self._raamatud

    @raamatud.setter
    def raamatud(self, raamatud: List[str]):
        """Sets the raamatud of this RaamatuNimekiri200Response.


        :param raamatud: The raamatud of this RaamatuNimekiri200Response.
        :type raamatud: List[str]
        """

        self._raamatud = raamatud
