from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from raamatu_teenus.models.base_model import Model
from raamatu_teenus import util


class RaamatustSoneOtsimine201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sone=None, raamatu_id=None, leitud=None):  # noqa: E501
        """RaamatustSoneOtsimine201Response - a model defined in OpenAPI

        :param sone: The sone of this RaamatustSoneOtsimine201Response.  # noqa: E501
        :type sone: str
        :param raamatu_id: The raamatu_id of this RaamatustSoneOtsimine201Response.  # noqa: E501
        :type raamatu_id: int
        :param leitud: The leitud of this RaamatustSoneOtsimine201Response.  # noqa: E501
        :type leitud: int
        """
        self.openapi_types = {
            'sone': str,
            'raamatu_id': int,
            'leitud': int
        }

        self.attribute_map = {
            'sone': 'sone',
            'raamatu_id': 'raamatu_id',
            'leitud': 'leitud'
        }

        self._sone = sone
        self._raamatu_id = raamatu_id
        self._leitud = leitud

    @classmethod
    def from_dict(cls, dikt) -> 'RaamatustSoneOtsimine201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The raamatustSoneOtsimine_201_response of this RaamatustSoneOtsimine201Response.  # noqa: E501
        :rtype: RaamatustSoneOtsimine201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sone(self) -> str:
        """Gets the sone of this RaamatustSoneOtsimine201Response.


        :return: The sone of this RaamatustSoneOtsimine201Response.
        :rtype: str
        """
        return self._sone

    @sone.setter
    def sone(self, sone: str):
        """Sets the sone of this RaamatustSoneOtsimine201Response.


        :param sone: The sone of this RaamatustSoneOtsimine201Response.
        :type sone: str
        """

        self._sone = sone

    @property
    def raamatu_id(self) -> int:
        """Gets the raamatu_id of this RaamatustSoneOtsimine201Response.


        :return: The raamatu_id of this RaamatustSoneOtsimine201Response.
        :rtype: int
        """
        return self._raamatu_id

    @raamatu_id.setter
    def raamatu_id(self, raamatu_id: int):
        """Sets the raamatu_id of this RaamatustSoneOtsimine201Response.


        :param raamatu_id: The raamatu_id of this RaamatustSoneOtsimine201Response.
        :type raamatu_id: int
        """

        self._raamatu_id = raamatu_id

    @property
    def leitud(self) -> int:
        """Gets the leitud of this RaamatustSoneOtsimine201Response.


        :return: The leitud of this RaamatustSoneOtsimine201Response.
        :rtype: int
        """
        return self._leitud

    @leitud.setter
    def leitud(self, leitud: int):
        """Sets the leitud of this RaamatustSoneOtsimine201Response.


        :param leitud: The leitud of this RaamatustSoneOtsimine201Response.
        :type leitud: int
        """

        self._leitud = leitud
