from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from raamatu_teenus.models.base_model import Model
from raamatu_teenus import util


class RaamatuLisamine201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tulemus=None, raamatu_id=None):  # noqa: E501
        """RaamatuLisamine201Response - a model defined in OpenAPI

        :param tulemus: The tulemus of this RaamatuLisamine201Response.  # noqa: E501
        :type tulemus: str
        :param raamatu_id: The raamatu_id of this RaamatuLisamine201Response.  # noqa: E501
        :type raamatu_id: int
        """
        self.openapi_types = {
            'tulemus': str,
            'raamatu_id': int
        }

        self.attribute_map = {
            'tulemus': 'tulemus',
            'raamatu_id': 'raamatu_id'
        }

        self._tulemus = tulemus
        self._raamatu_id = raamatu_id

    @classmethod
    def from_dict(cls, dikt) -> 'RaamatuLisamine201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The raamatuLisamine_201_response of this RaamatuLisamine201Response.  # noqa: E501
        :rtype: RaamatuLisamine201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tulemus(self) -> str:
        """Gets the tulemus of this RaamatuLisamine201Response.


        :return: The tulemus of this RaamatuLisamine201Response.
        :rtype: str
        """
        return self._tulemus

    @tulemus.setter
    def tulemus(self, tulemus: str):
        """Sets the tulemus of this RaamatuLisamine201Response.


        :param tulemus: The tulemus of this RaamatuLisamine201Response.
        :type tulemus: str
        """
        if tulemus is None:
            raise ValueError("Invalid value for `tulemus`, must not be `None`")  # noqa: E501

        self._tulemus = tulemus

    @property
    def raamatu_id(self) -> int:
        """Gets the raamatu_id of this RaamatuLisamine201Response.


        :return: The raamatu_id of this RaamatuLisamine201Response.
        :rtype: int
        """
        return self._raamatu_id

    @raamatu_id.setter
    def raamatu_id(self, raamatu_id: int):
        """Sets the raamatu_id of this RaamatuLisamine201Response.


        :param raamatu_id: The raamatu_id of this RaamatuLisamine201Response.
        :type raamatu_id: int
        """
        if raamatu_id is None:
            raise ValueError("Invalid value for `raamatu_id`, must not be `None`")  # noqa: E501

        self._raamatu_id = raamatu_id
